# Generated by Django 5.0.2 on 2025-05-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0002_apikey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dnsrecord',
            unique_together={('domain', 'name')},
        ),
        migrations.DeleteModel(
            name='UpdateLog',
        ),
        migrations.RemoveField(
            model_name='dnsrecord',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='dnsrecord',
            name='ttl',
        ),
        migrations.RemoveField(
            model_name='dnsrecord',
            name='update_interval',
        ),
    ]
