# Generated by Django 5.0.2 on 2025-05-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns_updater', '0003_alter_dnsrecord_unique_together_delete_updatelog_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
